[theme]
primaryColor = "#1DB954"              # vert Spotify (boutons, sliders…)
backgroundColor = "#191414"           # noir quasi-pur du fond
secondaryBackgroundColor = "#121212"  # gris très foncé (cartes, sidebars)
textColor = "#FFFFFF"                 # texte blanc
font = "sans serif"
